# Base image mit Qt 5.15.2 für ARM64
FROM docker.io/carlonluca/qt-dev:5.15.2

# Installiere nur das, was zusätzlich gebraucht wird
RUN apt-get update && apt-get install -y sqlite3 && apt-get clean

# Optional: Qt Pfad setzen, falls später gebraucht
ENV QT_DIR=/opt/Qt-arm64-5.15.2
ENV PATH=$QT_DIR/bin:$PATH
