name: Build and Release

on:
  push:
    branches:
      - '**' # Trigger on all branches

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up CMake
        uses: lukka/get-cmake@latest

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        uses: jurplel/install-qt-action@v4
        with:
          version: '5.15.2'
          host: 'linux'
          target: 'desktop'

      - name: Install SQLite (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libsqlite3-dev

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        uses: jurplel/install-qt-action@v4
        with:
          version: '5.15.2'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'

      - name: Install SQLite (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install sqlite

      - name: Configure the project
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build the project
        run: |
          cmake --build build --config Release

      - name: Archive build artifacts (only on master)
        if: github.ref == 'refs/heads/master'
        run: |
          mkdir -p dist
          cp build/Release/* dist/ || cp build/* dist/
        shell: bash

      - name: Upload build artifacts (only on master)
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-build
          path: dist/
