name: Build Qt App (ARM64) via Docker + QEMU

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Application in ARM64 Docker
        run: |
          docker run --rm --platform=linux/arm64 \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            carlonluca/qt-dev:5.15.2 \
            bash -c "apt-get update && \
            apt-get install -y sqlite3 && \
            mkdir -p build && \
            cd build && \
            cmake .. -DCMAKE_BUILD_TYPE=Release 2>&1 | tee ../cmake_config_log.txt && \
            make -j$(nproc) 2>&1 | tee ../make_build_log.txt"

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: QtBuild
          path: build/src/MyProject
