name: Build Qt Application with carlonluca/qt-dev:5.15.2 (ARM64)

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-22.04

    container:
      image: docker.io/carlonluca/qt-dev:5.15.2
      options: --platform linux/arm64  # Stellt sicher, dass ARM64 verwendet wird

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install bash and build dependencies
        run: |
          # Installiere bash und andere notwendige Tools
          apt-get update && apt-get install -y bash build-essential cmake sqlite3

      - name: Set up Qt environment
        run: |
          # Setze den Pfad zu den Qt-Binärdateien
          export PATH=/opt/Qt-arm64-5.15.2/bin:$PATH
          
          # Wechsle ins Projektverzeichnis
          cd ${GITHUB_WORKSPACE}

          # Erstelle das Build-Verzeichnis und konfiguriere den Build mit CMake
          mkdir -p build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release

          # Baue das Projekt mit make
          make -j$(nproc)
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: QtBuild
          path: build/src/MyProject
